spring.application.name=cloud-food-corner

server.port=1010

spring.datasource.url=jdbc:h2:mem:cloudfooddb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
